title: Ayushi Gandhi
logo: /assets/img/WhatsApp Image 2023-08-29 at 1.27.48 AM.jpeg
description: Software professional with nearly 6 years of experience in web development, with expertise in Angular,React and other Frontend frameworks. Experienced at working with foreign clients to successfully deliver projects. Strong communication and adaptive skills with experience in collaborating with global clients.
show_downloads: false

